import uuid
from django.db import models

from enumerations.enums import StudentLevel, InstructorGradeLevel

class User(models.Model):
    #AutoField is a primary key that is automatically generated by the database
    #starts from 1 and increments by 1
    #id=models.AutoField(primary_key=True)
    #or
    #UUIDField is a primary key that is a unique identifier for the user
    #uuid4 is a function that generates a random UUID (Universally Unique Identifier)
    #editable=False means that the field is not editable
    #UUID is a 128-bit identifier, which is a 36-character string in the format of 8-4-4-4-12
    #it's more secure than AutoField because it's not predictable
    id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.CharField(max_length=255)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=255)
    birth_date=models.DateField()
    gender=models.CharField(max_length=10)
    user_type=models.CharField(max_length=10)
    bio=models.TextField()
    profile_picture=models.ImageField(upload_to='profile_pictures/', 
                        null=True, blank=True)
    date_joined=models.DateTimeField(auto_now_add=True)
    class Meta:
        #abstract = True means that the model is not created in the database
        abstract = True
        #verbose_name is the property used into the admin interface to display the model name
        #verbose_name = 'User'
        #verbose_name_plural is the property used into the admin interface to display the model name in plural
        #verbose_name_plural = 'Users'
        #ordering is the property used to order the queryset by a field
        #the minus sign means that the ordering is descending
        ordering = ['-date_joined']
        #indexes is the property used to create indexes on the fields
        #the fields are the fields on which the index is created
        #the index is used to speed up the queries on the fields
        indexes = [
            models.Index(fields=['username', 'email']),
        ]

class Instructor(User):
    grade_level=models.CharField(max_length=20,choices=InstructorGradeLevel.choices,default=InstructorGradeLevel.ASSISTANT)
    class Meta:
        db_table = 'instructors'
        verbose_name = 'Instructor'
        verbose_name_plural = 'Instructors'
        
class Student(User):
    level=models.CharField(max_length=10,choices=StudentLevel.choices,default=StudentLevel.PRIMARY)
    score=models.FloatField(default=0.00)
    class Meta:
        db_table = 'students'
        verbose_name = 'Student'
        verbose_name_plural = 'Students'
        