import uuid
from django.db import models

class User(models.Model):
    #AutoField is a primary key that is automatically generated by the database
    #starts from 1 and increments by 1
    #id=models.AutoField(primary_key=True)
    #or
    #UUIDField is a primary key that is a unique identifier for the user
    #uuid4 is a function that generates a random UUID (Universally Unique Identifier)
    #editable=False means that the field is not editable
    #UUID is a 128-bit identifier, which is a 36-character string in the format of 8-4-4-4-12
    #it's more secure than AutoField because it's not predictable
    id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username=models.CharField(max_length=255)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=255)
    birth_date=models.DateField()
    gender=models.CharField(max_length=10)
    user_type=models.CharField(max_length=10)
    bio=models.TextField()
    profile_picture=models.ImageField(upload_to='profile_pictures/', 
                        null=True, blank=True)
    date_joined=models.DateTimeField(auto_now_add=True)
    