# Generated by Django 6.0.2 on 2026-03-10 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('grade_level', models.CharField(choices=[('Assistant', 'Assistant'), ('Lecturer', 'Lecturer'), ('Professor', 'Professor'), ('Senior Lecturer', 'Senior Lecturer'), ('Head of Department', 'Head Of Department'), ('Dean', 'Dean'), ('Provost', 'Provost'), ('Chancellor', 'Chancellor'), ('Other', 'Other')], default='Assistant', max_length=20)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[(1, 'student level 1'), (2, 'student level 2'), (3, 'student level 3'), (4, 'student level 4'), (5, 'student level 5'), (6, 'student level 6')], default=1, max_length=10)),
                ('score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
    ]
